services:
  faba-bench:
    build: .
    container_name: faba-front-bench
    shm_size: '2gb'
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
      - "3004:3004"
      - "3005:3005"
      - "3006:3006"
      - "4201:4202"
      - "4202:4202"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    privileged: true